
# cargo-vet audits file

[[audits.anyhow]]
who = "Marcus Griep <marcus@griep.us>"
criteria = "safe-to-deploy"
delta = "1.0.66 -> 1.0.69"

[[audits.bytes]]
who = "Marcus Griep <marcus@griep.us>"
criteria = "safe-to-deploy"
delta = "1.2.1 -> 1.4.0"

[[audits.either]]
who = "Marcus Griep <marcus@griep.us>"
criteria = "safe-to-deploy"
delta = "1.8.0 -> 1.8.1"

[[audits.fastrand]]
who = "Marcus Griep <marcus@griep.us>"
criteria = "safe-to-deploy"
delta = "1.8.0 -> 1.9.0"

[[audits.heck]]
who = "Marcus Griep <marcus@griep.us>"
criteria = "safe-to-deploy"
delta = "0.4.0 -> 0.4.1"

[[audits.indexmap]]
who = "Marcus Griep <marcus@griep.us>"
criteria = "safe-to-deploy"
delta = "1.9.1 -> 1.9.2"

[[audits.itertools]]
who = "Marcus Griep <marcus@griep.us>"
criteria = "safe-to-deploy"
delta = "0.10.5 -> 0.11.0"

[[audits.itertools]]
who = "Marcus Griep <marcus@griep.us>"
criteria = "safe-to-deploy"
delta = "0.12.1 -> 0.13.0"

[[audits.once_cell]]
who = "Marcus Griep <marcus@griep.us>"
criteria = "safe-to-deploy"
delta = "1.16.0 -> 1.17.1"

[[audits.once_cell]]
who = "Marcus Griep <marcus@griep.us>"
criteria = "safe-to-deploy"
delta = "1.17.1 -> 1.18.0"

[[audits.pbjson-build]]
who = "Marcus Griep <marcus@griep.us>"
criteria = "safe-to-deploy"
delta = "0.6.2 -> 0.7.0"

[[audits.petgraph]]
who = "Marcus Griep <marcus@griep.us>"
criteria = "safe-to-deploy"
delta = "0.6.2 -> 0.6.3"

[[audits.prettyplease]]
who = "Marcus Griep <marcus@griep.us>"
criteria = "safe-to-deploy"
delta = "0.1.21 -> 0.1.23"

[[audits.prettyplease]]
who = "Marcus Griep <marcus@griep.us>"
criteria = "safe-to-deploy"
delta = "0.1.23 -> 0.2.9"

[[audits.proc-macro2]]
who = "Marcus Griep <marcus@griep.us>"
criteria = "safe-to-deploy"
delta = "1.0.47 -> 1.0.51"

[[audits.proc-macro2]]
who = "Marcus Griep <marcus@griep.us>"
criteria = "safe-to-deploy"
delta = "1.0.51 -> 1.0.63"

[[audits.prost]]
who = "Marcus Griep <marcus@griep.us>"
criteria = "safe-to-deploy"
delta = "0.11.2 -> 0.11.8"

[[audits.prost]]
who = "Marcus Griep <marcus@griep.us>"
criteria = "safe-to-deploy"
delta = "0.11.8 -> 0.11.9"

[[audits.prost-build]]
who = "Marcus Griep <marcus@griep.us>"
criteria = "safe-to-deploy"
delta = "0.11.1 -> 0.11.8"

[[audits.prost-build]]
who = "Marcus Griep <marcus@griep.us>"
criteria = "safe-to-deploy"
delta = "0.11.8 -> 0.11.9"

[[audits.prost-derive]]
who = "Marcus Griep <marcus@griep.us>"
criteria = "safe-to-deploy"
delta = "0.11.2 -> 0.11.8"

[[audits.prost-derive]]
who = "Marcus Griep <marcus@griep.us>"
criteria = "safe-to-deploy"
delta = "0.11.8 -> 0.11.9"

[[audits.prost-types]]
who = "Marcus Griep <marcus@griep.us>"
criteria = "safe-to-deploy"
delta = "0.11.2 -> 0.11.8"

[[audits.prost-types]]
who = "Marcus Griep <marcus@griep.us>"
criteria = "safe-to-deploy"
delta = "0.11.8 -> 0.11.9"

[[audits.quote]]
who = "Marcus Griep <marcus@griep.us>"
criteria = "safe-to-deploy"
delta = "1.0.21 -> 1.0.23"

[[audits.quote]]
who = "Marcus Griep <marcus@griep.us>"
criteria = "safe-to-deploy"
delta = "1.0.23 -> 1.0.29"

[[audits.regex]]
who = "Marcus Griep <marcus@griep.us>"
criteria = "safe-to-deploy"
delta = "1.7.0 -> 1.7.1"

[[audits.regex]]
who = "Marcus Griep <marcus@griep.us>"
criteria = "safe-to-deploy"
delta = "1.7.1 -> 1.8.4"

[[audits.regex-syntax]]
who = "Marcus Griep <marcus@griep.us>"
criteria = "safe-to-deploy"
delta = "0.6.28 -> 0.7.2"

[[audits.syn]]
who = "Marcus Griep <marcus@griep.us>"
criteria = "safe-to-deploy"
delta = "1.0.103 -> 1.0.109"

[[audits.syn]]
who = "Marcus Griep <marcus@griep.us>"
criteria = "safe-to-deploy"
delta = "1.0.109 -> 2.0.22"

[[audits.tempfile]]
who = "Marcus Griep <marcus@griep.us>"
criteria = "safe-to-deploy"
delta = "3.3.0 -> 3.4.0"

[[audits.tonic-build]]
who = "Marcus Griep <marcus@griep.us>"
criteria = "safe-to-deploy"
delta = "0.8.2 -> 0.8.4"

[[audits.tonic-build]]
who = "Marcus Griep <marcus@griep.us>"
criteria = "safe-to-deploy"
delta = "0.8.4 -> 0.9.2"

[[audits.unicode-ident]]
who = "Marcus Griep <marcus@griep.us>"
criteria = "safe-to-deploy"
delta = "1.0.5 -> 1.0.6"

[[audits.which]]
who = "Marcus Griep <marcus@griep.us>"
criteria = "safe-to-deploy"
delta = "4.3.0 -> 4.4.0"

[[trusted.errno]]
criteria = "safe-to-deploy"
user-id = 6825 # Dan Gohman (sunfishcode)
start = "2023-08-29"
end = "2025-02-14"

[[trusted.linux-raw-sys]]
criteria = "safe-to-deploy"
user-id = 6825 # Dan Gohman (sunfishcode)
start = "2021-06-12"
end = "2025-02-14"

[[trusted.pbjson-build]]
criteria = "safe-to-deploy"
user-id = 133947 # Raphael Taylor-Davies (tustvold)
start = "2021-09-28"
end = "2025-02-14"

[[trusted.prettyplease]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2022-01-04"
end = "2025-08-22"

[[trusted.prost]]
criteria = "safe-to-deploy"
user-id = 3959 # Lucio Franco (LucioFranco)
start = "2021-07-08"
end = "2025-02-14"

[[trusted.prost-build]]
criteria = "safe-to-deploy"
user-id = 3959 # Lucio Franco (LucioFranco)
start = "2021-07-08"
end = "2025-02-14"

[[trusted.prost-derive]]
criteria = "safe-to-deploy"
user-id = 3959 # Lucio Franco (LucioFranco)
start = "2021-07-08"
end = "2025-02-14"

[[trusted.prost-types]]
criteria = "safe-to-deploy"
user-id = 3959 # Lucio Franco (LucioFranco)
start = "2021-07-08"
end = "2025-02-14"

[[trusted.rustix]]
criteria = "safe-to-deploy"
user-id = 6825 # Dan Gohman (sunfishcode)
start = "2021-10-29"
end = "2025-02-14"

[[trusted.syn]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-03-01"
end = "2025-08-22"

[[trusted.tonic-build]]
criteria = "safe-to-deploy"
user-id = 3959 # Lucio Franco (LucioFranco)
start = "2019-10-02"
end = "2025-02-14"

[[trusted.windows-sys]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2021-11-15"
end = "2025-02-14"

[[trusted.windows-targets]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2022-09-09"
end = "2025-02-14"

[[trusted.windows_aarch64_gnullvm]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2022-09-01"
end = "2025-02-14"

[[trusted.windows_aarch64_msvc]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2021-11-05"
end = "2025-02-14"

[[trusted.windows_i686_gnu]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2021-10-28"
end = "2025-02-14"

[[trusted.windows_i686_msvc]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2021-10-27"
end = "2025-02-14"

[[trusted.windows_x86_64_gnu]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2021-10-28"
end = "2025-02-14"

[[trusted.windows_x86_64_gnullvm]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2022-09-01"
end = "2025-02-14"

[[trusted.windows_x86_64_msvc]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2021-10-27"
end = "2025-02-14"
